NAME = rush-02

SOURCE = declarations.h main.c ft_checkargcthree.c ft_checkargctwo.c ft_checkargcwrong.c ft_checkdictname.c ft_checkunsigned.c ft_messages.c ft_messages2.c ft_putstr.c ft_unknownerror.c


$(NAME):
	gcc -o $(NAME) $(SOURCE)

fclean:
	/usr/bin/rm $(NAME) *.o

test:
	which gcc ; which rm
